language: cpp
dist: xenial
compiler: clang

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - make
      - libstdc++-8-dev
      - clang-9
      - llvm-9-dev
      - llvm-9-tools
      - libboost-dev
      - libgtest-dev

before_script:
  - export CC=clang-9
  - export CXX=clang++-9
  # libgtest-dev require compilation
  - mkdir gtest-build
  - cd gtest-build
  - cmake /usr/src/gtest/
  - make
  - sudo cp *.a /usr/local/lib
  - cd ..
  # Download, build, install required dependencies (not included as submodules)
  - cd dep
  # WebAssembly/wabt
  - git clone https://github.com/WebAssembly/wabt.git
  - cd wabt
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # Done with dependencies
  - cd ..
  # Generate build script for wembed
  - mkdir build
  - cd build
  - cmake ..

script: make && make test ARGS="-V"
