language: cpp
dist: xenial
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - make
      - clang-8
      - llvm-8-dev
      - libc++-8-dev
      - libc++abi-8-dev
      - libboost-dev

before_script:
  # Download, build, install required dependencies (not included as submodules)
  - cd dep
  # WebAssembly/wabt
  - git clone https://github.com/WebAssembly/wabt.git
  - cd wabt
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS="-stdlib=libc++" ..
  - make
  - sudo make install
  - cd ../..
  # Done with dependencies
  - cd ..
  # Generate build script for wembed
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_CXX_FLAGS="-stdlib=libc++" ..

script: make && make test
