language: cpp
dist: xenial
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - make
      - libstdc++-8-dev
      - clang-8
      - llvm-8-dev
      - libboost-dev
      - libgtest-dev

before_script:
  - export CC=clang-8
  - export CXX=clang++-8
  # libgtest-dev require compilation
  - mkdir gtest-build
  - cd gtest-build
  - cmake /usr/src/gtest/
  - make
  - sudo cp *.a /usr/local/lib
  - cd ..
  # Download, build, install required dependencies (not included as submodules)
  - cd dep
  # WebAssembly/wabt
  - git clone https://github.com/WebAssembly/wabt.git
  - cd wabt
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # Done with dependencies
  - cd ..
  # Generate build script for wembed
  - mkdir build
  - cd build
  - cmake ..

script: make && make test ARGS="-V"
