language: cpp
dist: xenial
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-7
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - make
      - clang-7
      - llvm-7-dev
      - libc++-7-dev
      - libc++abi-7-dev
      - libboost-dev

before_script:
  # Download, build, install required dependencies (not included as submodules)
  - cd dep
  # WebAssembly/wabt
  - git clone https://github.com/WebAssembly/wabt.git
  - cd wabt
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # Done with dependencies
  - cd ..
  # Generate build script for wembed
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
