language: cpp
dist: bionic
compiler: clang

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - make
      - libstdc++-8-dev
      - clang-10
      - llvm-10-dev
      - llvm-10-examples
      - llvm-10-tools
      - lld-10
      - libboost-dev
      - libgtest-dev

before_script:
  - export CC=clang-10
  - export CXX=clang++-10
  - export WASM_CC=clang-10
  - export WASM_NM=llvm-nm-10
  - export WASM_AR=llvm-ar-10
  #- export WASI_CFLAGS=-fuse-ld=lld-10
  # libgtest-dev require compilation
  - mkdir gtest-build
  - cd gtest-build
  - cmake /usr/src/gtest/
  - make
  - sudo cp *.a /usr/local/lib
  - cd ..
  # Download, build, install required dependencies (not included as submodules)
  - cd dep
  # WebAssembly/wabt
  - git clone https://github.com/WebAssembly/wabt.git
  - cd wabt
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # WASI libc
  - git clone https://github.com/CraneStation/wasi-libc
  - cd wasi-libc
  - make
  - export WASI_SYSROOT=`pwd`/sysroot
  - cd ..
  # libclang_rt
  - wget https://github.com/CraneStation/wasi-sdk/releases/download/wasi-sdk-7/libclang_rt.builtins-wasm32-wasi-7.0.tar.gz
  - sudo tar -xvzf libclang_rt.builtins-wasm32-wasi-7.0.tar.gz --directory /usr/lib/llvm-10/lib/clang/10.0.0/
  # Done with dependencies
  - cd ..
  # Generate build script for wembed
  - mkdir build
  - cd build
  - cmake ..

script: make && make test ARGS="-V"
